server:
  port: 8383
  address: 0.0.0.0

spring:
  profiles:
    active: dev
  datasource:
      # 配置数据源类型
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/class?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: XiaMuYao1314!
      # 初始化，最小，最大连接数
      initialSize: 3
      minidle: 3
      maxActive: 18
      # 获取数据库连接等待的超时时间
      maxWait: 60000
      # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: SELECT 1 FROM dual
      # 配置监控统计拦截的filters,去掉后，监控界面的sql无法统计
      filters: stat,wall,log4j
