spring:
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  mapper-locations: classpath:/mapper/api/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: top.xiamuyao.fastspringdevelop.api.entity

logging:
  level:
    top.xiamuyao.fastspringdevelop.api.mapper: debug