server:
  port: 8383
  address: 0.0.0.0

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/stumysql?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: XiaMuYao1314!
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true